[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[build.nixpacksPlan.phases.install]
cmds = ["cd ../.. && npm ci"]

[build.nixpacksPlan.phases.build]
cmds = [
  "cd ../.. && npm run build --workspace=@tannerbroberts/about-time-core",
  "cd ../.. && npm run build --workspace=@about-time/api-client",
  "cd ../.. && npm run build --workspace=@about-time/frontend"
]

[build.nixpacksPlan.start]
cmd = "npx serve -s dist -l $PORT"
